// Code generated by "golifx-import-products -output ./protocol/v2/device products/products.json"; DO NOT EDIT

package device

var (
	// Vendors automatically generated from products.json
	Vendors = map[uint32]Vendor{
		1: Vendor{
			ID: 1,
			Name: `LIFX`,
			Products: map[uint32]*Product{
				20: &Product{ID: 20, VendorID: 1, Name: `Color 1000 BR30`, Features: 2},
				22: &Product{ID: 22, VendorID: 1, Name: `Color 1000`, Features: 2},
				25: &Product{ID: 25, VendorID: 1, Name: `LIFX+ A19`, Features: 6},
				11: &Product{ID: 11, VendorID: 1, Name: `White 800 (High Voltage)`, Features: 0},
				18: &Product{ID: 18, VendorID: 1, Name: `White 900 BR30 (Low Voltage)`, Features: 0},
				10: &Product{ID: 10, VendorID: 1, Name: `White 800 (Low Voltage)`, Features: 0},
				26: &Product{ID: 26, VendorID: 1, Name: `LIFX+ BR30`, Features: 6},
				31: &Product{ID: 31, VendorID: 1, Name: `LIFX Z`, Features: 6},
				1: &Product{ID: 1, VendorID: 1, Name: `Original 1000`, Features: 2},
				3: &Product{ID: 3, VendorID: 1, Name: `Color 650`, Features: 2},
			},
		},
	}
)
